spring:
  profiles:
    active: nonprod
  application:
    name: document-api-business-service
  main:
    banner-mode: "off"
  data:
    mongodb:
      uri: mongodb://document_usr:12AB56@mdbhalbill1dev2.t-online.private:27017,mdbhalbill2dev2.t-online.private:27017,mdbhalbill3dev2.t-online.private:27017/document_api?readPreference=primary&connectTimeoutMS=1000&socketTimeoutMS=3000&ssl=true
  kafka:
    listener:
      logContainerConfig: true
      commitLogLevel: info
      ack-mode: batch
    properties:
      specific.avro.reader: true
      schema.registry.url: https://lwbidv21.int-dev.telekom.hu:8087,https://lwbidv22.int-dev.telekom.hu:8087,https://lwbidv23.int-dev.telekom.hu:8087
      basic.auth.credentials.source: SASL_INHERIT
      basic.auth.user.info: hal_document_api:LWBI1_hal_document_api
    topics:
      notificationEvent: hu-telekom-hal-notification-notificationevent
      deleteDocumentsEvent: hu-telekom-documentmanagement-deleteddocuments
    bootstrap-servers: lwbidv21.int-dev.telekom.hu:9092,lwbidv22.int-dev.telekom.hu:9092,lwbidv23.int-dev.telekom.hu:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: hu.mt.dps.springboot.kafka.serializer.KafkaAvroSerializerWithErrorHandling
      properties:
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username=hal_document_api password=LWBI1_hal_document_api;
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
        auto.register.schemas: false
e-store-document-download:
  urlPrefix: https://bilbelwidv2-lb.t-mobile.intra:8445/lwi/estore/document/
  username: _hal-document-api
  password: "Y#a2KQwTqm6F"

feign:
  httpclient:
    enabled: true
  hystrix:
    enabled: true
  client:
    config:
      customerBill:
        connectTimeout: 1000
        readTimeout: 20000
        url: https://dev2-hal-customer-bill-api.paas.telekom.hu
      geoAddress:
        connectTimeout: 1000
        readTimeout: 20000
        url:
          hostUrl: https://dev2-hal-geographic-address-mngt-api.paas.telekom.hu
          getAddress: /geographicAddressManagement/v1/addresses/{addressId}
      idVerification:
        connectTimeout: 1000
        readTimeout: 20000
        url:
          hostUrl: https://dev2-hal-customer-hub.paas.telekom.hu
          getIdVerification: /identityverification/int/v1/idVerifications/{id}
      productInventory:
        connectTimeout: 1000
        readTimeout: 20000
        url:
          hostUrl: https://dev2-hal-productinventory-api.paas.telekom.hu
          getProducts: /productInventory/int/v1/products
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: ${HYSTRIX_TIME_OUT:20000}

management:
  server:
    port: 9000
  endpoint:
    health:
      show-details: "ALWAYS"
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
      application.responsible.workgroup: IT.APIHAL4.OPS
      application.ci_id: CI2425480

server:
  port: 8000
  tomcat:
    max-threads: 400
    max-connections: 400
    accept-count: 40

concurrency:
  default:
    executor:
      queue:
        capacity: 40
      pool:
        size:
          core: 50
          max: 80

jwt:
  publickey:
    alias: jwt
  validation:
    clockskewinsec: 10
    allowedAudiences: OneApp

label:
  error:
    default: Általános hiba

apptruststore:
  path: classpath:app_truststore.jks
  password: changeit

# - Minden hívó alkalmazás saját kulcsot kell kapjon
# - A kulcsok a különböző szintű környezetekben nem lehetnek azonosak (DEV,TST,PROD)
security:
  clients:
    - name: hal-customer-bill-api
      apikey: k8s:dev2-hal-customer-bill-api:21bd2dad-fb05-4632-877d-3fde949e9711
      channels:
    - name: oneapp_bff
      apikey: ext:oneapp_bff:9f6d40ab-d5e5-485a-9778-7a86d43410cc
      channels:
    - name: ife
      apikey: ext:ife:7bab346e-9f8b-40fd-ade3-396bcfd514d9
      channels:
    - name: product-ordering
      apikey: k8s:dev2-hal-product-ordering-api:aacfc61d-f884-45f6-b020-519b1b6b1feb
      channels:
    - name: mt-onecare-bff
      apikey: k8s:dev2-mt-onecare-bff:004bfc2b-5cfb-4daa-8eaf-d65417d52aed
      channels:
    - name: mt-doc-handling-bff
      apikey: k8s:dev2-mt-doc-handling-bff:d38d10b9-fea8-4680-b89a-7fcf2ca6ecc8
      channels:
  clientApiKeys:
    customerBill: k8s:dev2-hal-document-api:d73fec0c-f814-467e-ad72-c07c564e8912
    geoAddress: k8s:dev2-document:3c9e9bdf-df53-44e7-a820-7caf1df75117
    idVerification: hal-document-api:4e545a65-4773-488c-8935-d128f78d5cf5
    product-inventory-api: ext:document-api:2f799aa2-2593-4e52-b607-7c8f4060b97c

prometheus:
  enableTimer: false
    # minden x. hivas lesz elkuldve
  measuredCounter: 5
wsdl:
  createProducedDocumentSoap:
    host: https://bilbelwidv2-lb.t-mobile.intra:8445
    url: /lwi/int_ms/createproduceddocument
  putDocumentV2Soap:
    host: https://bilbelwidv2-lb.t-mobile.intra:8445
    url: /lwi/estore/putdocument_v2
    username: hal_document_api
    password: LWI1hal_document_api
    timeout: 10000
